version: '3.3'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      # - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --pilot.token=<YOUR_PILOT_TOKEN>
      - --experimental.devPlugin.gopath=/plugins/go
      - --experimental.devPlugin.modulename=github.com/username/my-plugin
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /path/to/your/plugin:/plugins/go/src/github.com/username/my-plugin

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.middlewares=my-plugin
      - traefik.http.middlewares.my-plugin.plugin.dev.Headers.Foo.name=Bar