# The name of your plugin as displayed in the Traefik Pilot web UI.
displayName: Name of your plugin

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/username/my-plugin

# A brief description of what your plugin is doing.
summary: Description of what my plugin is doing

# Configuration data for your plugin.
# This is mandatory,
# and Traefik Pilot will try to execute the plugin with the configuration you provide as part of its startup validity tests.
testData:
  Headers:
    Foo: Bar